"""Rename 'user' table to 'users'

Revision ID: 4f76ab8cdcbe
Revises: 80a279c49fed
Create Date: 2025-12-15 12:17:32.884965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4f76ab8cdcbe"
down_revision: Union[str, Sequence[str], None] = "80a279c49fed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_table("project")

    # Rename 'user' table to 'users'
    op.rename_table("user", "users")

    # Drop the old indexes and recreate them with the correct plural table name
    # (This ensures database consistency, as table rename doesn't always update index names)

    # Drop old indexes (which are now attached to the 'users' table)
    op.drop_index(op.f("ix_user_email"), table_name="users")
    op.drop_index(op.f("ix_user_full_name"), table_name="users")
    op.drop_index(op.f("ix_user_username"), table_name="users")

    # Recreate new indexes with the proper pluralized naming convention
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_full_name"), "users", ["full_name"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("full_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("username", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("hashed_password", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("user_token", mysql.VARCHAR(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "project",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
