"""Apply final unique constraints and confirm User model structure

Revision ID: 80a279c49fed
Revises: 001
Create Date: 2025-12-06 08:08:34.872440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "80a279c49fed"
down_revision: Union[str, Sequence[str], None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic ###

    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_full_name", table_name="users")
    op.drop_index("ix_users_hashed_password", table_name="users")
    op.drop_index("ix_users_username", table_name="users")

    # Rename the table to prevent data loss
    op.rename_table("users", "user")

    # Create new indexes for the user table
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # Note: We do not need to drop the table or create a new one, as the rename handles the structure change
    #
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic
    # Drop current indexes
    op.drop_index("ix_user_username", table_name="user")
    op.drop_index("ix_user_full_name", table_name="user")
    op.drop_index("ix_user_email", table_name="user")

    # Rename the table back to the original name
    op.rename_table("user", "users")

    # Recreate the old indexes for 'users'
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_full_name", "users", ["full_name"], unique=False)
    op.create_index("ix_users_hashed_password", "users", ["hashed_password"], unique=False)
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    # ### end Alembic commands ###
